import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Header from "../components/Header/Header";
import Footer from "@/components/Footer/Footer";

import "./globals.css";

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeSans.variable} ${manropeSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
